USE codeup_test_db;
  INSERT INTO albums(artist, name, release_date, sales, genre)
  VALUES ('Guns N'' Roses', 'Appetite for Destruction', '1987', 21.6, 'Hard Rock'),
  VALUES ('Olivia Newton John, John Travolta', 'Grease: The Original Soundtrack from the Motion Picture', '1978', 14.4, 'Soundtrack'),
  VALUES ('The Beatles', 'Abbey Road', '1969', 14.4, 'Rock'),
  VALUES ('Nirvana', 'Nevermind', '1991', 16.7, 'Grunge'),
  VALUES ('Michael Jackson', 'Dangerous', '1991', 17.3, 'Rock'),
  VALUES ('Dire Straits', 'Brothers in Arms', '1985', 17.7, 'Roots Rock'),
  VALUES ('Bill Medley, Jennifer Warnes', 'Dirty Dancing', '1987', 17.9, 'Soundtrack'),
  VALUES ('Pink Floyd', 'The Wall', '1979', 18.6, 'Progressive Rock'),
  VALUES ('Led Zeppelin', 'Led Zeppelin IV', '1971', 29.0, 'Hard Rock'),
  VALUES ('James Horner', 'Titanic: Music from the Motion Picture', '1997', 18.1, 'Soundtrack'),
  VALUES ('The Beatles', 'Sgt. Pepper''s Lonely Hearts Club Band', '1987', 21.6, 'Hard Rock'),
  VALUES ('Guns N'' Roses', 'Appetite for Destruction', '1987', 21.6, 'Hard Rock'),
  VALUES ('Guns N'' Roses', 'Appetite for Destruction', '1987', 21.6, 'Hard Rock'),
  VALUES ('Guns N'' Roses', 'Appetite for Destruction', '1987', 21.6, 'Hard Rock'),
  VALUES ('Guns N'' Roses', 'Appetite for Destruction', '1987', 21.6, 'Hard Rock'),
  VALUES ('Guns N'' Roses', 'Appetite for Destruction', '1987', 21.6, 'Hard Rock'),
  VALUES ('Guns N'' Roses', 'Appetite for Destruction', '1987', 21.6, 'Hard Rock'),
  VALUES ('Guns N'' Roses', 'Appetite for Destruction', '1987', 21.6, 'Hard Rock'),
  VALUES ('Guns N'' Roses', 'Appetite for Destruction', '1987', 21.6, 'Hard Rock'),
  VALUES ('Guns N'' Roses', 'Appetite for Destruction', '1987', 21.6, 'Hard Rock'),
  VALUES ('Guns N'' Roses', 'Appetite for Destruction', '1987', 21.6, 'Hard Rock'),
  VALUES ('Guns N'' Roses', 'Appetite for Destruction', '1987', 21.6, 'Hard Rock'),
  VALUES ('Guns N'' Roses', 'Appetite for Destruction', '1987', 21.6, 'Hard Rock'),
  VALUES ('Guns N'' Roses', 'Appetite for Destruction', '1987', 21.6, 'Hard Rock'),
  VALUES ('Guns N'' Roses', 'Appetite for Destruction', '1987', 21.6, 'Hard Rock'),
  VALUES ('Guns N'' Roses', 'Appetite for Destruction', '1987', 21.6, 'Hard Rock'),
  VALUES ('Guns N'' Roses', 'Appetite for Destruction', '1987', 21.6, 'Hard Rock'),
  VALUES ('Guns N'' Roses', 'Appetite for Destruction', '1987', 21.6, 'Hard Rock'),
  VALUES ('Guns N'' Roses', 'Appetite for Destruction', '1987', 21.6, 'Hard Rock'),
  VALUES ('Guns N'' Roses', 'Appetite for Destruction', '1987', 21.6, 'Hard Rock'),
  VALUES ('Guns N'' Roses', 'Appetite for Destruction', '1987', 21.6, 'Hard Rock'),
  VALUES ('Guns N'' Roses', 'Appetite for Destruction', '1987', 21.6, 'Hard Rock'),
