USE codeup_test_db;
  INSERT INTO albums(artist, name, release_date, sales, genre)
  VALUES ('Olivia Newton John, John Travolta', 'Grease: The Original Soundtrack from the Motion Picture', '1978', 14.4, 'Soundtrack'),
         ('The Beatles', 'Abbey Road', '1969', 14.4, 'Rock'),
         ('Nirvana', 'Nevermind', '1991', 16.7, 'Grunge'),
         ('Michael Jackson', 'Dangerous', '1991', 17.3, 'Rock'),
         ('Dire Straits', 'Brothers in Arms', '1985', 17.7, 'Roots Rock'),
         ('Bill Medley, Jennifer Warnes', 'Dirty Dancing', '1987', 17.9, 'Soundtrack'),
         ('Pink Floyd', 'The Wall', '1979', 18.6, 'Progressive Rock'),
         ('James Horner', 'Titanic: Music from the Motion Picture', '1997', 18.1, 'Soundtrack'),
         ('The Beatles', 'Sgt. Pepper''s Lonely Hearts Club Band', '1967', 18.2, 'Rock'),
         ('Celine Dion', 'Let''s Talk About Love', '1997', 19.3, 'Pop'),
         ('Michael Jackson', 'Bad', '1987', 19.3, 'Pop'),
         ('Madonna', 'The Immaculate Collection', '1990', 19.4, 'Pop'),
         ('Bruce Springsteen', 'Born in the U.S.A', '1984', 19.6, 'Heartland Rock'),
         ('Celine Dion', 'Falling into You', '1996', 20.2, 'Pop'),
         ('Metallica', 'Metallica', '1991', 21.2, 'Heavy Metal'),
         ('Santana', 'Supernatural', '1999', 20.5, 'Latin Rock'),
         ('Guns N'' Roses', 'Appetite for Destruction', '1987', 21.6, 'Hard Rock'),
         ('ABBA', 'Gold: Greatest Hits', '1992', 22.7, 'Pop'),
         ('The Beatles', '1', '2000', 23.4, 'Rock'),
         ('Alanis Morissette', 'Jagged Little Pill', '1995', 24.4, 'Alternative Rock'),
         ('Adele', '21', '2011', 25.3, 'Pop'),
         ('Led Zeppelin', 'Led Zeppelin IV', '1971', 29.0, 'Hard Rock'),
         ('Shania Twain', 'Come On Over', '1997', 29.6, 'Country'),
         ('Meat Loaf', 'Bat Out of Hell', '1977', 21.5, 'Hard Rock'),
         ('Bee Gees', 'Saturday Night Fever', '1977', 21.6, 'Disco'),
         ('Pink Floyd', 'The Dark Side of the Moon', '1973', 24.2, 'Progressive Rock'),
         ('AC/DC', 'Back in Black', '1980', 26.1, 'Hard Rock'),
         ('Whitney Houston', 'The Bodyguard', '1992', 28.4, 'R&B'),
         ('Fleetwood Mac', 'Rumours', '1977', 27.9, 'Soft Rock'),
         ('Eagles', 'Hotel California', '1976', 31.5, 'Soft Rock'),
         ('Eagles', 'Their Greatest Hits (1971-1975)', '1976', 41.2, 'Country Rock'),
         ('Michael Jackson', 'Thriller', '1982', 47.3, 'Pop');
